[package]
name = "valkey-automerge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
automerge = "1.0.0-beta.3"
valkey-module = "0.1"
base64 = "0.22"
serde_json = "1.0"
chrono = "0.4"
